#!/bin/sh

if [ -f config.status ]; then
	make maintainer-clean
fi

./bootstrap && \
    ./configure	--prefix=/usr \
		--sysconfdir=/etc \
		--sbindir=/usr/bin \
		--enable-maintainer-mode \
		--enable-debug \
		--mandir=/usr/share/man \
		--localstatedir=/var \
		--enable-test \
		--enable-tools \
		--enable-dundee \
		--disable-datafiles $* \
		--disable-bluetooth \
		--disable-isimodem \
		--disable-qmimodem \
		--disable-rilmodem \
		--disable-cdmamodem \
		--disable-dependency-tracking
